package org.zjs.pojo;

public class ImageInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imageinfo.ID
     *
     * @mbg.generated Thu Oct 25 14:35:43 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imageinfo.url
     *
     * @mbg.generated Thu Oct 25 14:35:43 CST 2018
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imageinfo.ID
     *
     * @return the value of imageinfo.ID
     *
     * @mbg.generated Thu Oct 25 14:35:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imageinfo.ID
     *
     * @param id the value for imageinfo.ID
     *
     * @mbg.generated Thu Oct 25 14:35:43 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imageinfo.url
     *
     * @return the value of imageinfo.url
     *
     * @mbg.generated Thu Oct 25 14:35:43 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imageinfo.url
     *
     * @param url the value for imageinfo.url
     *
     * @mbg.generated Thu Oct 25 14:35:43 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}